from typing import Protocol, List, Optional
from .types import Frame, Detection, Event, Context, Metrics, SystemState, TopologyConfig

class InputHandler(Protocol):
    def get_frame(self) -> Frame: ...

class VisionDetector(Protocol):
    def detect(self, frame: Frame) -> List[Detection]: ...

class CognitiveCore(Protocol):
    def store(self, event: Event) -> None: ...
    def get_context(self) -> Context: ...

class SemanticFeedback(Protocol):
    def generate(self, context: Context, detections: List[Detection]) -> str: ...

class Evaluator(Protocol):
    def maybe_update(self, event: Event) -> Optional[Metrics]: ...

class TrainerLoop(Protocol):
    def maybe_train(self, metrics: Optional[Metrics]) -> None: ...

class TDAManager(Protocol):
    def update(self, state: SystemState) -> TopologyConfig: ...

class VisualInterface(Protocol):
    def render(self, frame: Frame, detections: List[Detection], text: str, state: SystemState) -> None: ...